### PR TITLE
Ported to 1.16

### PR DESCRIPTION
**Pull request by justliliandev**
No Direct changes, therefore no new version number

### CODE REVIEW

**Comment by justliliandev** [comment]
To Specify: I ported to 1.16.4 because it is to most recent 1.16 version

**Comment by austin0150** [comment]
This is awesome! I really appreciate the work put into this. 
My only ask is that an entry is added to the change log in the readme, to call out that this is now 1.0.6:1.16.4.

**Comment by justliliandev** [comment]
Done

**Comment by austin0150** [comment]
Cool! I'll work on getting this tagged and the new jar added to curseforge

**Comment by austin0150** [comment]
CurseForge has been updated. Do you mind if I give your GitHub handle a shout out in the description? @agnor99

**Pull request merged**
