### PR TITLE
Language Support, 1.16 Preparation

### LINKED ISSUE #10: Texts on GUI is hardcoded and cannot be found in the language file
This is very bad for globalization. Technically, all non-debug displayed texts should be localizable.

### PR DESCRIPTION
**Pull request by justliliandev**
Added Language Support
Cleaned up Code for 1.16
Removed unused imports

### CODE REVIEW

**Comment by austin0150** [comment]
Thank you for opening this pull request! I really appreciate the work you have added to the project and at a glance the code looks good. Of course I would like to test out the changes before I approve. I'm a bit busy between work and school, but I fully intend to test these changes and approve them soon. Which version of forge did you use to build/run this?

**Comment by justliliandev** [comment]
I have not changed the forge version, so it should be the one specified in the build.gradle file.

**Comment by austin0150** [comment]
Was finally able to do some testing (I have re-installed windows since the last time I worked on this and had to remember how to run mods, lol). Everything seems good, My only request before I approve is that
- Line 16 of the build.gradle is updated to 1.0.6
- Line 18 of the mods.toml is updated to 1.0.6
- The readme is updated with change notes, following the current format

After I approve and merge, I will work on getting the updated version into CurseForge

Thanks again for your contribution!

**Review by austin0150 — APPROVED** [review]

**Comment by austin0150** [comment]
1.0.6-1.15.2 Release has been tagged and added to curse forge. Will hopefully be approved by curseforge in the next couple hours

**Pull request merged**
